name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: getting version tag
      run: VERSION=`cat version.txt`>> $GITHUB_ENV
    - name: Use dynamic variable
      run: echo "The version is $VERSION"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hossted/publisher:${VERSION}
    - name: logon to Docker
      run: docker login -u hossted -p ${{ secrets.hossted_docker }}
    - name: tag latest
      run: docker tag hossted/publisher:${VERSION} hossted/publisher:latest
    - name: pushing to Dockerhub
      run: docker push hossted/publisher:${VERSION}
    - name: pushing latest
      run: docker push hossted/publisher:latest
